---

- name: restart chronyd
  service:
    name: "{{ nettime_service }}"
    enabled: true
    state: restarted

- name: restart timedated
  systemd:
    name: systemd-timedated
    daemon_reload: true
    enabled: true
    state: restarted
