---

- name: restart nettime7
  systemd:
    name: systemd-timedated
    daemon_reload: true
    enabled: true
    state: started

- name: restart nettime6
  service:
    name: chronyd
    enabled: true
    state: started
