---

- name: Restart chronyd
  service:
    name: "{{ nettime_service }}"
    enabled: true
    state: restarted

- name: Start chronyd
  service:
    name: "{{ nettime_service }}"
    state: "{{ start_nettime_service }}"

- name: Restart timedated
  systemd:
    name: systemd-timedated
    daemon_reload: true
    enabled: true
    state: restarted
...
