---
# Standards: 0.2
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: base-nettime-centos7
    image: centos:7
    command: /sbin/init
    capabilities:
      - CAP_SYS_TIME
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: base-nettime-centos8
    image: centos:8
    command: /sbin/init
    capabilities:
      - CAP_SYS_TIME
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: base-nettime-debian10
    image: dokken/debian-10
    command: /lib/systemd/systemd
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
